server:
  port: 8091
spring:
  profiles:
    active: dev
  application:
    name: device-open-status
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://39.104.49.84:3306/dianfeng
    username: root
    password: Ywh@68531026!
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 39.104.49.84
    port: 6379
    database: 0
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
      max-wait: -1

ywh:
  mqtt:
    broker: 39.104.49.84
    port: 1883
    qos: 1
  redis:
    address: redis://39.104.49.84:6379


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

security:
  basic:
    enabled: false
